POST http://localhost:8080/books HTTP/1.1
content-type: application/json
Authorization: Bearer r-Vc_-XdwLOk4NEcYvWKlLvLa89fujeq

{
    "title": "The Lord of the Rings",
    "author": "6539d796b2638d07a20df3f6",
    "year": 1954
}
